name: github pages

on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: install
      run: yarn install --frozen-lockfile

    - name: build
      run: yarn run build

    - name: export
      run: yarn run export

    - name: add nojekyll
      run: touch ./out/.nojekyll

    - name: Copy CNAME
      run: cp CNAME out/CNAME

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
